set-option -g default-shell /bin/zsh
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set-option -g status-position top

set -g prefix ^A
set -g mouse on
set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g renumber-windows on
set -g set-clipboard on
setw -g mode-keys vi

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "none"

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect' # save environment
set -g @plugin 'tmux-plugins/tmux-continuum' # open environment
set -g @plugin 'christoomey/vim-tmux-navigator' #vim Keybindings
set -g @plugin 'omerxx/tmux-floax' # floating window
set -g @plugin 'sainnhe/tmux-fzf' # must have for sessionx
set -g @plugin 'omerxx/tmux-sessionx'

# sessionx
set -g @sessionx-bind 'o'
#set -g @sessionx-x-path '~/dotfiles'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'

# floating window config
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'white'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

# Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind '"'
bind h split-window -v -c "#{pane_current_path}"
unbind '%'
bind v split-window -h -c "#{pane_current_path}"

unbind p
unbind -n M-p
unbind n
unbind -n M-n

# Window styling
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_number_color "#{@thm_blue}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"

# Status module configuration
# Session module
set -g @catppuccin_session_icon " "
set -g @catppuccin_session_icon_bg "#{@thm_mauve}"
set -g @catppuccin_session_icon_fg "#{@thm_crust}"
set -g @catppuccin_session_text " #S"
set -g @catppuccin_session_text_bg " #{@thm_mantle}"
set -g @catppuccin_session_text_fg " #{@thm_text}"

# Directory module
set -g @catppuccin_directory_icon " "
set -g @catppuccin_directory_icon_bg "#{@thm_teal}"
set -g @catppuccin_directory_icon_fg "#{@thm_crust}"
set -g @catppuccin_directory_text " #{b:pane_current_path}"
set -g @catppuccin_directory_text_bg " #{@thm_mantle}"
set -g @catppuccin_directory_text_fg " #{@thm_text}"

# Date & time module
set -g @catppuccin_date_time_icon "󰃰 "
set -g @catppuccin_date_time_icon_bg "#{@thm_sapphire}"
set -g @catppuccin_date_time_icon_fg "#{@thm_crust}"
set -g @catppuccin_date_time_text " %H:%M"
set -g @catppuccin_date_time_text_bg " #{@thm_mantle}"
set -g @catppuccin_date_time_text_fg " #{@thm_text}"

set -g @catppuccin_status_left_separator " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_connect_separator "no"

# Status line configuration
set -g status-left-length 30
set -g status-left "#{E:@catppuccin_status_session}"
#set -g status-right "#{E:@catppuccin_status_directory}#{E:@catppuccin_status_date_time}"
set -g status-right "#{E:@catppuccin_status_date_time}"

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'

set -g status-bg default
set -g status-style bg=default
